@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.ssafy.zip.user.model.mapper.UserMapper",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_109727380 { 
   	label=ssafy
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_82814151 { 
   	label=zip
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   UserController1817088075[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)UserController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   userService: UserService [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ delete(userNo: int): ResponseEntity&lt;?&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ findPass(userId: String): ResponseEntity&lt;?&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ idCheck(userId: String): ResponseEntity&lt;?&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ login(userDto: UserDto): ResponseEntity&lt;?&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ modify(userDto: UserDto): ResponseEntity&lt;?&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ nickNameCheck(nickName: String): ResponseEntity&lt;?&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ regist(userDto: UserDto): ResponseEntity&lt;?&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ userInfo(userNo: int): ResponseEntity&lt;?&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ userList(): ResponseEntity&lt;?&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

UserMapper933366379[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)UserMapper</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ deleteUser(userNo: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getPass(userId: String): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ idCheck(userId: String): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ listUser(): List&lt;UserDto&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ loginUser(memberDto: UserDto): UserDto</TD></TR>
<TR><TD ALIGN="LEFT" >+ modifyUser(memberDto: UserDto)</TD></TR>
<TR><TD ALIGN="LEFT" >+ nickNameCheck(nickName: String): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ registUser(memberDto: UserDto): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ userInfo(userNo: int): UserDto</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

UserServiceImpl2017953311[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)UserServiceImpl</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   userMapper: UserMapper [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ deleteUser(userNo: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ findPass(userId: String): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ idCheck(userId: String): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ listUser(): List&lt;UserDto&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ loginUser(userDto: UserDto): UserDto</TD></TR>
<TR><TD ALIGN="LEFT" >+ modifyUser(userDto: UserDto)</TD></TR>
<TR><TD ALIGN="LEFT" >+ nickNameCheck(nickName: String): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ registUser(userDto: UserDto): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ userInfo(userNo: int): UserDto</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
UserController1817088075 -> UserServiceImpl2017953311[label="userService
[0..1]", arrowhead=none];
UserServiceImpl2017953311 -> UserMapper933366379[label="userMapper
[0..1]"];
    
}
@enduml